[2020-03-19 14:28:13,153][MainThread:25052][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 14:28:42,010][Thread-7:15276][task_id:django.server][basehttp.py:157][INFO]["GET /polls/ HTTP/1.1" 200 1035]
[2020-03-19 14:31:08,447][MainThread:25052][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-19 14:31:11,952][MainThread:23860][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 14:31:25,302][Thread-7:7592][task_id:django.server][basehttp.py:157][INFO]["GET /polls/ HTTP/1.1" 200 1035]
[2020-03-19 15:06:41,150][MainThread:23860][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\polls\views.py changed, reloading.]
[2020-03-19 15:06:43,941][MainThread:24840][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:07:26,788][MainThread:24840][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\polls\views.py changed, reloading.]
[2020-03-19 15:07:29,213][MainThread:17208][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:07:40,617][Thread-7:24700][task_id:django.server][basehttp.py:157][INFO]["GET /polls/ HTTP/1.1" 200 1035]
[2020-03-19 15:17:16,617][MainThread:17208][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\urls.py changed, reloading.]
[2020-03-19 15:17:19,716][MainThread:24344][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:23:16,366][MainThread:22280][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:23:25,714][Thread-7:25524][task_id:django.server][basehttp.py:157][INFO]["GET /user HTTP/1.1" 301 0]
[2020-03-19 15:23:25,744][Thread-7:25524][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 2]
[2020-03-19 15:28:33,438][MainThread:22280][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-19 15:28:35,842][MainThread:20864][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:39:23,556][MainThread:20864][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\user\admin.py changed, reloading.]
[2020-03-19 15:39:26,628][MainThread:12444][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:39:43,027][MainThread:12444][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\user\admin.py changed, reloading.]
[2020-03-19 15:39:46,011][MainThread:23212][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:39:55,897][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7927]
[2020-03-19 15:39:55,931][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/base.css HTTP/1.1" 304 0]
[2020-03-19 15:39:55,939][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/dashboard.css HTTP/1.1" 304 0]
[2020-03-19 15:39:55,946][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/responsive.css HTTP/1.1" 304 0]
[2020-03-19 15:39:56,196][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7927]
[2020-03-19 15:39:56,219][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/fonts.css HTTP/1.1" 304 0]
[2020-03-19 15:39:56,238][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0]
[2020-03-19 15:39:56,241][Thread-9:25352][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0]
[2020-03-19 15:39:56,242][Thread-11:23860][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0]
[2020-03-19 15:39:56,250][Thread-13:9856][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0]
[2020-03-19 15:39:56,251][Thread-15:24908][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0]
[2020-03-19 15:40:16,094][Thread-15:24908][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/add/ HTTP/1.1" 200 5523]
[2020-03-19 15:40:16,141][Thread-9:25352][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0]
[2020-03-19 15:40:16,145][Thread-13:9856][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/forms.css HTTP/1.1" 304 0]
[2020-03-19 15:40:16,145][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/core.js HTTP/1.1" 304 0]
[2020-03-19 15:40:16,160][Thread-15:24908][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363]
[2020-03-19 15:40:16,161][Thread-11:23860][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-19 15:40:16,306][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0]
[2020-03-19 15:40:16,313][Thread-9:25352][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/actions.js HTTP/1.1" 304 0]
[2020-03-19 15:40:16,315][Thread-15:24908][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0]
[2020-03-19 15:40:16,330][Thread-13:9856][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/urlify.js HTTP/1.1" 304 0]
[2020-03-19 15:40:16,336][Thread-11:23860][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/change_form.js HTTP/1.1" 200 712]
[2020-03-19 15:40:16,343][Thread-7:25228][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495]
[2020-03-19 15:40:16,347][Thread-15:24908][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/widgets.css HTTP/1.1" 200 10322]
[2020-03-19 15:40:16,349][Thread-17:24700][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0]
[2020-03-19 15:40:40,515][Thread-15:24908][task_id:django.request][log.py:228][ERROR][Internal Server Error: /admin/user/user/add/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'site_data.user_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1638, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1558, in _changeform_view
    form_validated = form.is_valid()
  File "D:\python\Envs\system_env\lib\site-packages\django\forms\forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "D:\python\Envs\system_env\lib\site-packages\django\forms\forms.py", line 175, in errors
    self.full_clean()
  File "D:\python\Envs\system_env\lib\site-packages\django\forms\forms.py", line 378, in full_clean
    self._post_clean()
  File "D:\python\Envs\system_env\lib\site-packages\django\forms\models.py", line 410, in _post_clean
    self.validate_unique()
  File "D:\python\Envs\system_env\lib\site-packages\django\forms\models.py", line 419, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\base.py", line 999, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\base.py", line 1103, in _perform_unique_checks
    if qs.exists():
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 777, in exists
    return self.query.has_results(using=self.db)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\sql\query.py", line 537, in has_results
    return compiler.has_results()
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\sql\compiler.py", line 1121, in has_results
    return bool(self.execute_sql(SINGLE))
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'site_data.user_user' doesn't exist")
[2020-03-19 15:40:40,537][Thread-15:24908][task_id:django.server][basehttp.py:157][ERROR]["POST /admin/user/user/add/ HTTP/1.1" 500 221739]
[2020-03-19 15:51:01,943][MainThread:23212][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-19 15:51:04,827][MainThread:24868][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:52:18,531][MainThread:24868][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-19 15:52:20,691][MainThread:13912][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:52:31,196][MainThread:16460][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:53:13,829][MainThread:16460][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-19 15:53:25,356][MainThread:25280][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 15:54:34,139][Thread-9:21180][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7927]
[2020-03-19 15:54:34,358][Thread-7:21384][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/add/ HTTP/1.1" 200 5523]
[2020-03-19 15:54:34,360][Thread-7:21384][task_id:django.server][basehttp.py:157][ERROR]["GET /admin/user/user/add/ HTTP/1.1" 500 59]
[2020-03-19 15:54:35,077][Thread-9:21180][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7927]
[2020-03-19 15:54:38,911][Thread-9:21180][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 2]
[2020-03-19 16:02:07,489][Thread-21:23468][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 2]
[2020-03-19 16:04:32,553][MainThread:25280][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\migrations\0001_initial.py changed, reloading.]
[2020-03-19 16:04:35,209][MainThread:24876][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 16:19:16,729][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7927]
[2020-03-19 16:19:17,829][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7927]
[2020-03-19 16:19:19,901][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/add/ HTTP/1.1" 200 5523]
[2020-03-19 16:19:19,985][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-19 16:19:25,663][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["POST /admin/user/user/add/ HTTP/1.1" 302 0]
[2020-03-19 16:19:25,953][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/add/ HTTP/1.1" 200 5736]
[2020-03-19 16:19:26,027][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-19 16:19:26,127][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0]
[2020-03-19 16:22:46,831][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/ HTTP/1.1" 200 2484]
[2020-03-19 16:22:48,583][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/ HTTP/1.1" 200 4406]
[2020-03-19 16:22:48,620][Thread-7:25308][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/changelists.css HTTP/1.1" 304 0]
[2020-03-19 16:22:48,816][Thread-13:25576][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-19 16:22:48,886][Thread-13:25576][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0]
[2020-03-19 16:24:38,414][MainThread:24876][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-19 16:24:43,295][MainThread:17972][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 16:24:49,519][MainThread:17972][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-19 16:24:53,657][MainThread:21116][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 16:24:59,322][MainThread:21116][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-19 16:25:02,308][MainThread:20940][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 16:26:06,483][MainThread:20940][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-19 16:26:12,062][MainThread:24144][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-19 16:29:38,653][Thread-7:24084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 211]
[2020-03-19 16:30:53,871][Thread-7:24084][task_id:django.server][basehttp.py:157][INFO]["GET /user/login HTTP/1.1" 301 0]
[2020-03-19 16:30:53,892][Thread-7:24084][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 622]
[2020-03-19 16:31:19,961][Thread-7:24084][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 716]
[2020-03-19 16:49:08,405][Thread-33:24596][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 1820]
[2020-03-19 16:49:20,122][Thread-33:24596][task_id:django.request][log.py:228][WARNING][Not Found: /login/]
[2020-03-19 16:49:20,125][Thread-33:24596][task_id:django.server][basehttp.py:157][WARNING]["POST /login/ HTTP/1.1" 404 2411]
[2020-03-19 16:49:56,735][Thread-33:24596][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 1825]
[2020-03-19 16:50:11,749][Thread-33:24596][task_id:django.security.csrf][log.py:228][WARNING][Forbidden (CSRF token missing or incorrect.): /user/login/]
[2020-03-19 16:50:11,755][Thread-33:24596][task_id:django.server][basehttp.py:157][WARNING]["POST /user/login/ HTTP/1.1" 403 2508]
[2020-03-23 09:01:20,911][MainThread:24144][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\migrations\0001_initial.py changed, reloading.]
[2020-03-23 09:01:25,705][MainThread:22256][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 09:58:08,706][MainThread:25676][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:01:15,359][Thread-7:24936][task_id:django.request][log.py:228][WARNING][Not Found: /]
[2020-03-23 10:01:15,364][Thread-7:24936][task_id:django.server][basehttp.py:157][WARNING]["GET / HTTP/1.1" 404 2482]
[2020-03-23 10:01:22,568][Thread-7:24936][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 195]
[2020-03-23 10:01:25,658][Thread-7:24936][task_id:django.request][log.py:228][WARNING][Not Found: /user/log]
[2020-03-23 10:01:25,660][Thread-7:24936][task_id:django.server][basehttp.py:157][WARNING]["GET /user/log HTTP/1.1" 404 3120]
[2020-03-23 10:01:33,251][Thread-7:24936][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:01:33,320][Thread-7:24936][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:01:34,645][Thread-9:27484][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/b25985c4c8cbda820bfb5b2693c30eea54e83421/ HTTP/1.1" 200 4783]
[2020-03-23 10:01:45,852][Thread-9:27484][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 302 0]
[2020-03-23 10:06:05,332][Thread-9:27484][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:06:05,413][Thread-9:27484][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:06:05,519][Thread-11:25100][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/15a4c3c8412379fe8f0cdcd2d4d67a4cdac52628/ HTTP/1.1" 200 4282]
[2020-03-23 10:06:07,219][Thread-11:25100][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:06:07,272][Thread-11:25100][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:06:07,387][Thread-13:19164][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/1529cfb7b56e39ac3b25fb8c252c1c7146924aab/ HTTP/1.1" 200 4380]
[2020-03-23 10:06:14,401][Thread-13:19164][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 1662]
[2020-03-23 10:06:14,464][Thread-13:19164][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:06:16,925][Thread-17:25808][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 1662]
[2020-03-23 10:06:17,026][Thread-17:25808][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:06:19,358][Thread-19:26024][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 1662]
[2020-03-23 10:06:19,418][Thread-19:26024][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:11:55,710][MainThread:25676][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:12:00,407][MainThread:26324][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:12:33,241][MainThread:26324][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:12:38,166][MainThread:27288][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:12:44,730][Thread-7:25692][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:12:44,761][Thread-7:25692][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:12:45,880][Thread-11:25368][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/3fc1d6e4cccaac6d2d972eae48a41f966537d596/ HTTP/1.1" 200 4665]
[2020-03-23 10:12:54,610][Thread-11:25368][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 2876]
[2020-03-23 10:12:54,657][Thread-11:25368][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:12:54,841][Thread-15:25776][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/89b751cc003ebe71beb017f237e0026d1b96969d/ HTTP/1.1" 200 4222]
[2020-03-23 10:13:07,995][Thread-15:25776][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 2876]
[2020-03-23 10:13:08,041][Thread-15:25776][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:13:08,251][Thread-17:23848][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/c4062b0c575d50ddd202de742f6e0c45f29815fb/ HTTP/1.1" 200 4539]
[2020-03-23 10:13:17,773][Thread-17:23848][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 2843]
[2020-03-23 10:13:17,820][Thread-17:23848][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:13:18,023][Thread-19:25816][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/8b34b2d65966ff9d599aea3379cac32a1e1424a1/ HTTP/1.1" 200 4985]
[2020-03-23 10:13:28,746][Thread-19:25816][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 2876]
[2020-03-23 10:13:28,806][Thread-19:25816][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:13:29,003][Thread-21:26532][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/2f3aa076dc48182e984bd69a9e6935e9b37f8369/ HTTP/1.1" 200 4206]
[2020-03-23 10:14:12,570][Thread-21:26532][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 2876]
[2020-03-23 10:14:12,623][Thread-21:26532][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:14:13,003][Thread-23:22336][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/245d866e0ad3b03e96d1817e66a1c0bb7abf07c9/ HTTP/1.1" 200 5026]
[2020-03-23 10:14:23,551][Thread-23:22336][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 302 0]
[2020-03-23 10:14:23,583][Thread-23:22336][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:15:51,978][MainThread:27288][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:15:56,633][MainThread:27152][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:16:58,941][MainThread:27152][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:17:03,099][MainThread:26248][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:17:04,427][Thread-7:25692][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:17:06,432][Thread-7:25692][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:17:07,448][Thread-7:25692][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:18:46,404][MainThread:26248][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:18:51,812][MainThread:27412][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:18:58,410][MainThread:27412][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:19:02,231][MainThread:24052][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:19:16,255][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,284][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,307][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,322][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,339][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,357][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,375][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,391][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,406][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,423][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,439][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,460][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,475][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,491][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,506][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,523][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,542][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,558][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,579][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,597][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,721][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,759][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,788][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,811][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,828][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,859][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,876][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,891][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,905][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,920][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,934][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,949][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,963][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,978][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:16,994][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,007][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,021][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,035][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,050][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,063][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,852][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,883][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,928][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:17,973][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,011][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,037][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,072][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,105][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,139][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,166][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,197][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,230][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,259][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,294][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,327][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,352][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,381][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,417][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,468][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:18,495][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,221][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,249][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,267][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,290][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,316][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,343][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,365][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,381][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,399][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,414][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,432][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,449][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,467][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,482][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,500][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,517][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,533][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,551][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,569][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:19,588][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,218][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,238][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,256][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,272][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,291][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,308][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,322][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,336][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,352][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,367][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,381][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,394][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,408][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,420][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,433][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,445][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,458][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,470][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,483][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:20,495][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,033][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,085][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,157][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,204][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,246][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,288][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,316][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,349][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,387][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,425][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,457][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,485][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,523][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,558][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,596][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,624][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,686][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,730][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,773][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:21,804][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,243][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,310][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,339][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,372][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,403][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,445][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,487][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,523][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,560][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,598][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,633][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,667][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,700][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,736][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,779][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,818][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,847][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,887][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,919][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:23,958][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,164][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,237][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,306][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,352][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,427][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,449][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,472][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,490][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,514][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,541][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,561][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,582][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,603][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,628][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,656][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,700][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,720][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,744][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,765][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:29,785][Thread-7:27540][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:19:37,718][MainThread:24052][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:19:41,934][MainThread:25604][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:19:46,585][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:47,461][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:47,881][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:48,178][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:48,335][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:48,468][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:49,066][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:49,486][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:49,685][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:49,819][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:49,964][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:50,099][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:19:58,609][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:20:35,884][Thread-7:19084][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:21:02,064][MainThread:25604][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:21:05,864][MainThread:20828][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:21:19,578][MainThread:20828][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:21:24,479][MainThread:26504][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:22:02,361][MainThread:26504][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:22:07,773][MainThread:25980][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:22:11,510][Thread-7:23616][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:23:27,916][Thread-7:23616][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 200]
[2020-03-23 10:23:35,204][Thread-7:23616][task_id:django.request][log.py:228][WARNING][Not Found: /logout/]
[2020-03-23 10:23:35,208][Thread-7:23616][task_id:django.server][basehttp.py:157][WARNING]["GET /logout/ HTTP/1.1" 404 2521]
[2020-03-23 10:24:17,679][Thread-7:23616][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 205]
[2020-03-23 10:24:21,142][Thread-7:23616][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/logout/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view user.views.logout didn't return an HttpResponse object. It returned None instead.
[2020-03-23 10:24:21,148][Thread-7:23616][task_id:django.server][basehttp.py:157][ERROR]["GET /user/logout/ HTTP/1.1" 500 67506]
[2020-03-23 10:24:26,475][Thread-7:23616][task_id:django.server][basehttp.py:157][INFO]["GET /user/logout/ HTTP/1.1" 302 0]
[2020-03-23 10:24:26,835][Thread-7:23616][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:24:26,922][Thread-7:23616][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:24:28,345][Thread-15:11932][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/b7773e7910abe7421dc6dc82d939a744cf0b68a7/ HTTP/1.1" 200 4695]
[2020-03-23 10:24:29,655][Thread-15:11932][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 302 0]
[2020-03-23 10:24:40,383][Thread-15:11932][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 200 2876]
[2020-03-23 10:24:40,476][Thread-15:11932][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:24:40,747][Thread-23:23764][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/3d048c6549400afb1a5507ada0ba3ee94e4fb746/ HTTP/1.1" 200 4906]
[2020-03-23 10:24:49,789][Thread-23:23764][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 302 0]
[2020-03-23 10:24:49,819][Thread-23:23764][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 205]
[2020-03-23 10:24:52,950][Thread-23:23764][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/logout/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view user.views.logout didn't return an HttpResponse object. It returned None instead.
[2020-03-23 10:24:52,957][Thread-23:23764][task_id:django.server][basehttp.py:157][ERROR]["GET /user/logout/ HTTP/1.1" 500 67506]
[2020-03-23 10:25:25,869][MainThread:25980][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:25:30,974][MainThread:26720][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:25:45,851][MainThread:26720][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:25:50,468][MainThread:24644][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:25:52,520][Thread-7:27116][task_id:django.server][basehttp.py:157][INFO]["GET /user/logout/ HTTP/1.1" 302 0]
[2020-03-23 10:25:52,773][Thread-7:27116][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:25:52,813][Thread-7:27116][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:25:53,681][Thread-9:22552][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/c53c11c475f5507a018ce709af1aca7ba255736f/ HTTP/1.1" 200 4791]
[2020-03-23 10:26:02,717][Thread-9:22552][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 302 0]
[2020-03-23 10:26:02,757][Thread-9:22552][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 205]
[2020-03-23 10:26:04,650][Thread-9:22552][task_id:django.server][basehttp.py:157][INFO]["GET /user/logout/ HTTP/1.1" 302 0]
[2020-03-23 10:26:04,787][Thread-9:22552][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:26:04,844][Thread-9:22552][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:26:05,132][Thread-15:20360][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/e367b1f33fba24fee3df13c728ff8aa79b036d80/ HTTP/1.1" 200 4947]
[2020-03-23 10:27:30,931][Thread-15:20360][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 302 0]
[2020-03-23 10:27:30,965][Thread-15:20360][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 205]
[2020-03-23 10:29:08,183][MainThread:24644][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\forms.py changed, reloading.]
[2020-03-23 10:29:13,123][MainThread:26788][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:52:04,129][Thread-7:23848][task_id:django.server][basehttp.py:157][INFO]["GET /user/logout/ HTTP/1.1" 302 0]
[2020-03-23 10:52:04,319][Thread-7:23848][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:52:04,368][Thread-7:23848][task_id:django.server][basehttp.py:157][WARNING]["GET /static/login/css/login.css HTTP/1.1" 404 1683]
[2020-03-23 10:52:06,095][Thread-9:23464][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/d9fc568a478eb36b46c1be84a9d8a9a206d5774a/ HTTP/1.1" 200 3938]
[2020-03-23 10:55:55,440][Thread-9:23464][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2732]
[2020-03-23 10:55:55,452][Thread-9:23464][task_id:django.server][basehttp.py:157][INFO]["GET /static/login/css/login.css HTTP/1.1" 200 726]
[2020-03-23 10:55:55,554][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/bd0ad140f4ab98ea31b48f91f3d4ad06ef1370a2/ HTTP/1.1" 200 4651]
[2020-03-23 10:55:55,808][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /static/login/image/bg.jpg HTTP/1.1" 200 53306]
[2020-03-23 10:56:29,548][Thread-11:25780][task_id:django.request][log.py:228][WARNING][Not Found: /register/]
[2020-03-23 10:56:29,552][Thread-11:25780][task_id:django.server][basehttp.py:157][WARNING]["GET /register/ HTTP/1.1" 404 2527]
[2020-03-23 10:57:37,472][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2737]
[2020-03-23 10:57:37,612][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/d84eb0e80dc9b5f67f5e4405c49704e18a002e18/ HTTP/1.1" 200 3926]
[2020-03-23 10:57:39,837][Thread-11:25780][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 78, in register
    return render(request, 'login/register.html')
  File "D:\python\Envs\system_env\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\python\Envs\system_env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python\Envs\system_env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login/register.html
[2020-03-23 10:57:39,842][Thread-11:25780][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 90610]
[2020-03-23 10:58:01,690][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /user/register HTTP/1.1" 301 0]
[2020-03-23 10:58:02,146][Thread-11:25780][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 78, in register
    return render(request, 'login/register.html')
  File "D:\python\Envs\system_env\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\python\Envs\system_env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\python\Envs\system_env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: login/register.html
[2020-03-23 10:58:02,155][Thread-11:25780][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 90228]
[2020-03-23 10:58:26,047][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 1522]
[2020-03-23 10:58:26,089][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /static/login/css/register.css HTTP/1.1" 200 270]
[2020-03-23 10:58:27,615][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 1522]
[2020-03-23 10:58:31,085][Thread-11:25780][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 1522]
[2020-03-23 10:59:26,086][MainThread:26788][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:59:31,268][MainThread:26440][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:59:37,591][MainThread:26440][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 10:59:42,624][MainThread:27260][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 10:59:48,809][Thread-7:27356][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 10:59:48,815][Thread-7:27356][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 76002]
[2020-03-23 11:00:17,607][MainThread:27260][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:00:22,386][MainThread:25712][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:00:24,541][Thread-7:26568][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 11:00:24,548][Thread-7:26568][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 75847]
[2020-03-23 11:00:27,076][Thread-7:26568][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 11:00:27,083][Thread-7:26568][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 75946]
[2020-03-23 11:00:28,217][Thread-7:26568][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 11:00:28,221][Thread-7:26568][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 75946]
[2020-03-23 11:00:29,358][Thread-7:26568][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 11:00:29,361][Thread-7:26568][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 75946]
[2020-03-23 11:00:29,744][Thread-7:26568][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 11:00:29,750][Thread-7:26568][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 75979]
[2020-03-23 11:00:29,752][Thread-7:26568][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 59]
[2020-03-23 11:00:29,909][Thread-9:26240][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 11:00:29,915][Thread-9:26240][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 75979]
[2020-03-23 11:00:29,917][Thread-9:26240][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 59]
[2020-03-23 11:00:30,038][Thread-11:23508][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 114, in register
    register_form = forms.RegisterForm()
AttributeError: module 'django.forms' has no attribute 'RegisterForm'
[2020-03-23 11:00:30,042][Thread-11:23508][task_id:django.server][basehttp.py:157][ERROR]["GET /user/register/ HTTP/1.1" 500 75979]
[2020-03-23 11:00:46,459][MainThread:25712][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:00:51,648][MainThread:25088][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:01:01,933][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 3776]
[2020-03-23 11:01:03,005][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/3788764c4e3c8e838ca5605b42f999ff5d0b9232/ HTTP/1.1" 200 4333]
[2020-03-23 11:01:37,541][Thread-7:4260][task_id:django.request][log.py:228][WARNING][Not Found: /register/]
[2020-03-23 11:01:37,544][Thread-7:4260][task_id:django.server][basehttp.py:157][WARNING]["POST /register/ HTTP/1.1" 404 2528]
[2020-03-23 11:02:03,456][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 3781]
[2020-03-23 11:02:03,622][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/ed6842b2c87edf2864b1029f4cc4805a05d69bcb/ HTTP/1.1" 200 4551]
[2020-03-23 11:04:49,810][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["POST /user/register/ HTTP/1.1" 200 3924]
[2020-03-23 11:04:49,977][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/f659cffa2228f323b3ec5d6ee299ac4ab44bb204/ HTTP/1.1" 200 4810]
[2020-03-23 11:05:12,965][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["POST /user/register/ HTTP/1.1" 302 0]
[2020-03-23 11:05:13,088][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2737]
[2020-03-23 11:05:13,279][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/d5acc24cff63ff26e1b68ea750c41f1709f48239/ HTTP/1.1" 200 4550]
[2020-03-23 11:05:25,286][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["POST /user/login/ HTTP/1.1" 302 0]
[2020-03-23 11:05:25,315][Thread-7:4260][task_id:django.server][basehttp.py:157][INFO]["GET /user/ HTTP/1.1" 200 205]
[2020-03-23 11:05:53,059][MainThread:25088][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:05:58,397][MainThread:25664][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:06:03,232][MainThread:25664][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:06:07,435][MainThread:26500][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:07:33,390][MainThread:26500][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:07:37,051][MainThread:25676][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:09:13,979][MainThread:25676][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:09:17,845][MainThread:27060][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:10:42,948][MainThread:27060][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:10:47,292][MainThread:26316][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:11:11,924][MainThread:26316][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:11:14,125][MainThread:22236][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:11:34,577][MainThread:22236][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:11:39,532][MainThread:27640][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:12:44,735][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 302 0]
[2020-03-23 11:12:45,437][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /admin/login/?next=/admin/ HTTP/1.1" 200 1916]
[2020-03-23 11:12:45,641][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/base.css HTTP/1.1" 304 0]
[2020-03-23 11:12:45,654][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/login.css HTTP/1.1" 200 1233]
[2020-03-23 11:12:45,661][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/responsive.css HTTP/1.1" 304 0]
[2020-03-23 11:12:45,793][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 302 0]
[2020-03-23 11:12:45,929][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /admin/login/?next=/admin/ HTTP/1.1" 200 1916]
[2020-03-23 11:12:45,963][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/fonts.css HTTP/1.1" 304 0]
[2020-03-23 11:12:45,987][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0]
[2020-03-23 11:12:45,988][Thread-9:26900][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0]
[2020-03-23 11:12:51,961][Thread-9:26900][task_id:django.server][basehttp.py:157][INFO]["POST /admin/login/?next=/admin/ HTTP/1.1" 302 0]
[2020-03-23 11:12:52,122][Thread-9:26900][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7904]
[2020-03-23 11:12:52,143][Thread-9:26900][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/dashboard.css HTTP/1.1" 304 0]
[2020-03-23 11:12:52,167][Thread-9:26900][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0]
[2020-03-23 11:12:52,176][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0]
[2020-03-23 11:12:52,180][Thread-11:27644][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0]
[2020-03-23 11:12:54,481][Thread-11:27644][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/ HTTP/1.1" 200 4620]
[2020-03-23 11:12:54,532][Thread-9:26900][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,534][Thread-11:27644][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/changelists.css HTTP/1.1" 304 0]
[2020-03-23 11:12:54,566][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:12:54,667][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,669][Thread-13:27144][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,670][Thread-11:27644][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/actions.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,672][Thread-17:25860][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,685][Thread-7:25220][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,687][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/core.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,691][Thread-9:26900][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/urlify.js HTTP/1.1" 304 0]
[2020-03-23 11:12:54,768][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0]
[2020-03-23 11:13:01,097][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["POST /admin/user/user/ HTTP/1.1" 200 3507]
[2020-03-23 11:13:01,128][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/cancel.js HTTP/1.1" 200 409]
[2020-03-23 11:13:02,796][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["POST /admin/user/user/ HTTP/1.1" 302 0]
[2020-03-23 11:13:03,044][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/ HTTP/1.1" 200 3364]
[2020-03-23 11:13:03,157][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:13:03,298][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0]
[2020-03-23 11:13:06,469][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/logout/ HTTP/1.1" 200 1197]
[2020-03-23 11:14:32,213][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2737]
[2020-03-23 11:14:33,327][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/a0654f55d15e0420a45050dfb5a9453bef491065/ HTTP/1.1" 200 4111]
[2020-03-23 11:14:35,542][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 3781]
[2020-03-23 11:14:35,621][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/c11210d6040772e6aa69fadfe7abbe0921ee46cc/ HTTP/1.1" 200 4018]
[2020-03-23 11:14:52,107][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["POST /user/register/ HTTP/1.1" 302 0]
[2020-03-23 11:14:52,226][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2737]
[2020-03-23 11:14:52,314][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/3fa6f82d1bb7803b05f7bdbd654e2d2c9e6bcfb4/ HTTP/1.1" 200 4623]
[2020-03-23 11:14:56,833][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 302 0]
[2020-03-23 11:14:56,954][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/login/?next=/admin/ HTTP/1.1" 200 1916]
[2020-03-23 11:14:57,779][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 302 0]
[2020-03-23 11:14:57,909][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/login/?next=/admin/ HTTP/1.1" 200 1916]
[2020-03-23 11:15:04,359][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["POST /admin/login/?next=/admin/ HTTP/1.1" 302 0]
[2020-03-23 11:15:04,525][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7758]
[2020-03-23 11:15:04,589][Thread-15:20536][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392]
[2020-03-23 11:23:48,904][Thread-19:26276][task_id:django.server][basehttp.py:157][INFO]["GET /admin/auth/user/ HTTP/1.1" 200 6717]
[2020-03-23 11:23:48,987][Thread-19:26276][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:23:51,027][Thread-21:21692][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/search.svg HTTP/1.1" 200 458]
[2020-03-23 11:23:51,199][Thread-21:21692][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097]
[2020-03-23 11:24:02,231][Thread-21:21692][task_id:django.server][basehttp.py:157][INFO]["GET /admin/auth/user/1/change/ HTTP/1.1" 200 15348]
[2020-03-23 11:24:02,270][Thread-21:21692][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/forms.css HTTP/1.1" 304 0]
[2020-03-23 11:24:02,301][Thread-19:26276][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:24:02,431][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/calendar.js HTTP/1.1" 200 7777]
[2020-03-23 11:24:02,433][Thread-27:24084][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/SelectBox.js HTTP/1.1" 200 5753]
[2020-03-23 11:24:02,437][Thread-19:26276][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/css/widgets.css HTTP/1.1" 200 10322]
[2020-03-23 11:24:02,443][Thread-25:27148][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20232]
[2020-03-23 11:24:02,446][Thread-29:23616][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12318]
[2020-03-23 11:24:02,460][Thread-29:23616][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/change_form.js HTTP/1.1" 200 712]
[2020-03-23 11:24:02,477][Thread-29:23616][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495]
[2020-03-23 11:24:02,703][Thread-27:24084][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655]
[2020-03-23 11:24:02,704][Thread-29:23616][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677]
[2020-03-23 11:24:02,705][Thread-19:26276][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291]
[2020-03-23 11:24:02,712][Thread-25:27148][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086]
[2020-03-23 11:24:02,722][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655]
[2020-03-23 11:24:31,167][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["POST /admin/auth/user/1/change/ HTTP/1.1" 302 0]
[2020-03-23 11:24:31,609][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/auth/user/add/ HTTP/1.1" 200 6058]
[2020-03-23 11:24:31,706][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:24:34,009][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/auth/ HTTP/1.1" 200 2961]
[2020-03-23 11:24:36,074][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/auth/user/ HTTP/1.1" 200 6715]
[2020-03-23 11:24:36,134][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:24:40,236][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/ HTTP/1.1" 200 7728]
[2020-03-23 11:24:42,600][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/ HTTP/1.1" 200 4407]
[2020-03-23 11:24:42,657][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:24:44,073][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/3/change/ HTTP/1.1" 200 5836]
[2020-03-23 11:24:44,160][Thread-23:26916][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:28:21,936][MainThread:27640][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\models.py changed, reloading.]
[2020-03-23 11:28:26,942][MainThread:25792][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:28:46,635][MainThread:25792][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\models.py changed, reloading.]
[2020-03-23 11:28:51,220][MainThread:27592][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:29:01,671][MainThread:27592][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\admin.py changed, reloading.]
[2020-03-23 11:29:05,415][MainThread:24268][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:29:42,985][MainThread:24268][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:29:47,679][MainThread:18076][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:30:35,300][MainThread:18076][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:30:39,944][MainThread:26484][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:31:05,396][MainThread:26484][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:31:10,434][MainThread:22780][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:31:25,688][MainThread:22780][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:31:31,172][MainThread:27528][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:33:00,153][MainThread:27528][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-23 11:33:04,446][MainThread:27312][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:33:26,814][MainThread:27312][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-23 11:33:31,830][MainThread:26120][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:34:09,420][MainThread:26120][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:34:14,356][MainThread:27288][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:35:09,542][MainThread:27288][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:35:13,994][MainThread:27636][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:37:04,897][MainThread:27636][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\urls.py changed, reloading.]
[2020-03-23 11:37:09,605][MainThread:27180][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:39:11,841][MainThread:27180][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:39:17,069][MainThread:25792][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:40:01,146][Thread-7:25820][task_id:django.request][log.py:228][ERROR][Internal Server Error: /admin/user/user/3/change/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1641, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1543, in _changeform_view
    obj = self.get_object(request, unquote(object_id), to_field)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 755, in get_object
    return queryset.get(**{field.name: object_id})
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 411, in get
    num = len(clone)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")
[2020-03-23 11:40:01,182][Thread-7:25820][task_id:django.server][basehttp.py:157][ERROR]["GET /admin/user/user/3/change/ HTTP/1.1" 500 205281]
[2020-03-23 11:40:05,429][Thread-7:25820][task_id:django.request][log.py:228][ERROR][Internal Server Error: /admin/user/user/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1796, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")
[2020-03-23 11:40:05,447][Thread-7:25820][task_id:django.server][basehttp.py:157][ERROR]["GET /admin/user/user/ HTTP/1.1" 500 188243]
[2020-03-23 11:40:09,253][Thread-7:25820][task_id:django.request][log.py:228][ERROR][Internal Server Error: /admin/user/user/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1796, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")
[2020-03-23 11:40:09,275][Thread-7:25820][task_id:django.server][basehttp.py:157][ERROR]["GET /admin/user/user/ HTTP/1.1" 500 187858]
[2020-03-23 11:40:12,385][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/ HTTP/1.1" 200 2944]
[2020-03-23 11:40:15,128][Thread-7:25820][task_id:django.request][log.py:228][ERROR][Internal Server Error: /admin/user/user/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\python\Envs\system_env\lib\site-packages\django\contrib\admin\options.py", line 1796, in changelist_view
    'selection_note': _('0 of %(cnt)s selected') % {'cnt': len(cl.result_list)},
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 258, in __len__
    self._fetch_all()
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\models\sql\compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "D:\python\Envs\system_env\lib\site-packages\django\db\backends\mysql\base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "D:\python\Envs\system_env\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'user_user.has_confirmed' in 'field list'")
[2020-03-23 11:40:15,141][Thread-7:25820][task_id:django.server][basehttp.py:157][ERROR]["GET /admin/user/user/ HTTP/1.1" 500 187891]
[2020-03-23 11:41:28,347][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/ HTTP/1.1" 200 4407]
[2020-03-23 11:41:28,425][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:41:30,601][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/3/change/ HTTP/1.1" 200 6261]
[2020-03-23 11:41:30,687][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:41:34,723][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["POST /admin/user/user/3/change/ HTTP/1.1" 302 0]
[2020-03-23 11:41:35,020][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /admin/user/user/ HTTP/1.1" 200 4588]
[2020-03-23 11:41:35,075][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /admin/jsi18n/ HTTP/1.1" 200 7722]
[2020-03-23 11:41:43,394][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 3781]
[2020-03-23 11:41:44,714][Thread-7:25820][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/6834c9ed8af0a80b9fee4868af864decff50dc80/ HTTP/1.1" 200 4635]
[2020-03-23 11:42:02,132][Thread-7:25820][task_id:django.request][log.py:228][ERROR][Internal Server Error: /user/register/]
Traceback (most recent call last):
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\python\Envs\system_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 150, in register
    send_email(email, code)
  File "D:\python\py_workspace\python_practice\site_demo\apps\user\views.py", line 47, in send_email
    msg.send()
  File "D:\python\Envs\system_env\lib\site-packages\django\core\mail\message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "D:\python\Envs\system_env\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "D:\python\Envs\system_env\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "d:\python\py_env_manager\python37\lib\smtplib.py", line 730, in login
    raise last_exception
  File "d:\python\py_env_manager\python37\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "d:\python\py_env_manager\python37\lib\smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 authentication failed')
[2020-03-23 11:42:02,144][Thread-7:25820][task_id:django.server][basehttp.py:157][ERROR]["POST /user/register/ HTTP/1.1" 500 112948]
[2020-03-23 11:43:10,730][MainThread:25792][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\site_demo\settings.py changed, reloading.]
[2020-03-23 11:43:15,688][MainThread:15476][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:43:17,871][Thread-7:21980][task_id:django.server][basehttp.py:157][INFO]["GET /user/register/ HTTP/1.1" 200 3781]
[2020-03-23 11:43:18,562][Thread-7:21980][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/2d23d4227b32d309719665e1e6448067dcaa9d20/ HTTP/1.1" 200 5207]
[2020-03-23 11:43:51,577][Thread-7:21980][task_id:django.server][basehttp.py:157][INFO]["POST /user/register/ HTTP/1.1" 200 3936]
[2020-03-23 11:43:51,785][Thread-7:21980][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/4fa96075546d2b9236917050eff832ad47e988a9/ HTTP/1.1" 200 5020]
[2020-03-23 11:44:16,666][Thread-7:21980][task_id:django.server][basehttp.py:157][INFO]["POST /user/register/ HTTP/1.1" 302 0]
[2020-03-23 11:44:16,749][Thread-7:21980][task_id:django.server][basehttp.py:157][INFO]["GET /user/login/ HTTP/1.1" 200 2737]
[2020-03-23 11:44:16,960][Thread-7:21980][task_id:django.server][basehttp.py:157][INFO]["GET /captcha/image/f9a248a9c60e156f6529b901ddaf833a87d1df9f/ HTTP/1.1" 200 4146]
[2020-03-23 11:50:45,283][MainThread:15476][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:50:50,478][MainThread:22736][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:51:19,704][MainThread:22736][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:51:24,533][MainThread:26660][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:51:44,929][MainThread:26660][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:51:50,033][MainThread:26760][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-03-23 11:51:58,847][MainThread:26760][task_id:django.utils.autoreload][autoreload.py:222][INFO][D:\python\py_workspace\python_practice\site_demo\apps\user\views.py changed, reloading.]
[2020-03-23 11:52:03,978][MainThread:27612][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
